-- AlterTable
ALTER TABLE "invoice_bills" ADD COLUMN     "balanceDue" DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "bankDetails" JSONB,
ADD COLUMN     "baseAmount" DECIMAL(15,2),
ADD COLUMN     "baseCurrency" TEXT DEFAULT 'INR',
ADD COLUMN     "buyerAddress" TEXT,
ADD COLUMN     "buyerCountry" TEXT,
ADD COLUMN     "buyerName" TEXT,
ADD COLUMN     "buyerTaxId" TEXT,
ADD COLUMN     "confirmedAt" TIMESTAMP(3),
ADD COLUMN     "countryOfDestination" TEXT,
ADD COLUMN     "countryOfOrigin" TEXT,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "discount" DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "exchangeRate" DECIMAL(10,4),
ADD COLUMN     "iecCode" TEXT,
ADD COLUMN     "incoterms" TEXT,
ADD COLUMN     "invoiceType" TEXT NOT NULL DEFAULT 'TAX',
ADD COLUMN     "jurisdiction" TEXT,
ADD COLUMN     "lateFeePolicy" TEXT,
ADD COLUMN     "lutFiled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "paymentLink" TEXT,
ADD COLUMN     "paymentTerms" TEXT,
ADD COLUMN     "pdfStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED',
ADD COLUMN     "placeOfSupply" TEXT,
ADD COLUMN     "reverseCharge" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reverseReason" TEXT,
ADD COLUMN     "sacCode" TEXT,
ADD COLUMN     "sellerAddress" TEXT,
ADD COLUMN     "sellerCountry" TEXT,
ADD COLUMN     "sellerEmail" TEXT,
ADD COLUMN     "sellerName" TEXT,
ADD COLUMN     "sellerPhone" TEXT,
ADD COLUMN     "sellerTaxId" TEXT,
ADD COLUMN     "shipToAddress" TEXT,
ADD COLUMN     "shipToName" TEXT,
ADD COLUMN     "shippingCost" DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "taxSummary" JSONB,
ADD COLUMN     "taxType" TEXT NOT NULL DEFAULT 'NONE';
